apiVersion: v1
kind: Secret
metadata:
  name: vocab-agent-secrets
type: Opaque
stringData:
  DB_USER: "root"
  DB_PASSWORD: "password"
  REDIS_PASSWORD: "Msdian-77"
  OPENAI_API_KEY: "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"
  ANTHROPIC_API_KEY: "change_me"
  ACP_JWT_SECRET: "secretmdkemdokp4i98985908606805609706ktk0509i05968905087096870698"
