spring.profiles.active=local
spring.profiles.include=engine

kafka.bootstrap-servers=localhost:9092
kafka.poll-timeout-ms=3000
kafka.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.value-deserializer=com.notify.agent.consumers.serializers.EventCaptureDeserializer
kafka.client-id=my-client
kafka.fetch-max-wait-ms=500
kafka.fetch-min-bytes=1
kafka.fetch-max-bytes=52428800
kafka.max-partition-fetch-bytes=1048576
kafka.max-message-bytes=1048588
kafka.isolation-level=read_uncommitted
kafka.enable-auto-commit=false
kafka.heartbeat-interval-ms=3000
kafka.session-timeout-ms=10000
kafka.auto-offset-reset=earliest
kafka.group-instance-id=UNIQUE-ID
kafka.max-poll-interval-ms=300000
kafka.max-poll-records=500

kafka:
  bootstrap-servers: kafka-broker:9094
  security:
    protocol: SASL_PLAINTEXT
    sasl-mechanism: SCRAM-SHA-256
    sasl-jaas-config: >
      org.apache.kafka.common.security.scram.ScramLoginModule required
      username="notify-service"
      password="${KAFKA_PASSWORD}";
 


