spring:
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
      group-id: vocab-adk-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        max.poll.records: 50

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:vocabdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  quartz:
    properties:
      org.quartz.threadPool.threadCount: 2

vocab:
  kafka-topic: ${VOCAB_TOPIC:vocabulary-raw}
  openai-model: ${OPENAI_MODEL:gpt-4o-mini}
  openai-max-tokens: 160
  description-max-length: 512

redis:
  host: ${REDIS_HOST:redis-19139.crce263.ap-south-1-1.ec2.cloud.redislabs.com}
  port: ${REDIS_PORT:19139}
  username: ${REDIS_USERNAME:test}
  password: ${REDIS_PASSWORD:Msdian-77}        # or null for no auth
  database: 0
  timeout: 2000        # ms - connect timeout
  lettuce:
    shutdown-timeout: 100     # ms
    pool:
      max-active: 32
      max-idle: 16
      min-idle: 4
      max-wait: 2000          # ms

logging:
  level:
    root: INFO

connector:
  channel:
    WEBHOOK:
      clazz: "com.example.agent.connectors.WebhookConnector"
      instances: 1
    EMAIL:
      clazz: "com.example.agent.connectors.SmtpEmailConnector"
      instances: 1
